spring:
  application:
    name: ecommerce-product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/ecommerce_product?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
  servlet:
    context-path: /product
